##### BEGIN external/Dockerfile/iamge-header #####
FROM bash:5.0.9
##### END external/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/build-instructions #####
RUN apk update && apk add coreutils && apk add gettext && apk add jq && rm -rf /var/cache/apk/*
##### END image/Dockerfile/build-instructions #####

##### BEGIN external/Dockerfile/conteco #####
COPY ./ /conteco/git-repository/
##### END external/Dockerfile/conteco #####

##### BEGIN external/Dockerfile/labels-footer #####
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="external" \
      io.vcweb.name="bash" \
      io.vcweb.tag="5.0.9" \
      io.vcweb.build="external" \
      io.vcweb.label="Exernal Bash image" \
      io.vcweb.description="Import of external Bash image into the ContEco ecosystem." \
      io.vcweb.repository="/conteco/git-repository" 
##### END external/Dockerfile/labels-footer #####
