#!/usr/bin/env bash

export CONTECO_LABEL="conteco.external.bash - ContEco"
export CONTECO_DESCRIPTION="Official Bash image with ContEco external prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="bash"
export CONTECO_TAG="5.0.18"

export CONTECO_BASE="${CONTECO_NAME}:${CONTECO_TAG}"
export CONTECO_BUILD="external"
